import { SideBar } from "@/components/sidebar/SideBar";
import "@/css/common.scss";
import type { Metadata } from "next";

import localFont from "next/font/local";
import "tailwindcss/tailwind.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Распознавание объектов",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex">
          <div className="h-[100vh] flex justify-center flex-col gap-2 mr-2">
            <SideBar />
          </div>
          <div className="w-full p-4 bg-[#2a2a2a]">{children}</div>
        </div>
      </body>
    </html>
  );
}
